use crate::config::actions::ButtonActionConfig;
use crate::config::rings::*;

#[derive(Debug, Clone, Copy)]
pub struct BrowserTexts {
    pub profile_label: &'static str,
    // Slot 0: New Tab
    pub new_tab: &'static str,
    // Slot 1: Tabs group
    pub tabs_group: &'static str,
    pub reopen_closed_tab: &'static str,
    pub next_tab: &'static str,
    pub prev_tab: &'static str,
    pub close_other_tabs: &'static str,
    // Slot 2: Close Tab
    pub close_tab: &'static str,
    // Slot 3: Navigation group
    pub navigation_group: &'static str,
    pub back_page: &'static str,
    pub forward_page: &'static str,
    pub refresh: &'static str,
    pub force_refresh: &'static str,
    pub home_page: &'static str,
    // Slot 4: Search & URL group
    pub search_group: &'static str,
    pub address_bar: &'static str,
    pub find_in_page: &'static str,
    pub find_next: &'static str,
    pub find_prev: &'static str,
    // Slot 5: View group
    pub view_group: &'static str,
    pub fullscreen: &'static str,
    pub reader_mode: &'static str,
    pub reset_zoom: &'static str,
    pub view_source: &'static str,
    // Slot 6: Tools group
    pub tools_group: &'static str,
    pub history: &'static str,
    pub downloads: &'static str,
    pub bookmarks_manager: &'static str,
    pub dev_tools: &'static str,
    // Slot 7: Windows & Security group
    pub windows_group: &'static str,
    pub incognito: &'static str,
    pub new_window: &'static str,
    pub add_bookmark: &'static str,
    pub print_page: &'static str,
}

pub const BROWSER_TRANSLATIONS: &[(&str, BrowserTexts)] = &[
    (
        "en",
        BrowserTexts {
            profile_label: "Web Browsers",
            new_tab: "New Tab",
            tabs_group: "Tabs",
            reopen_closed_tab: "Reopen Closed Tab",
            next_tab: "Next Tab",
            prev_tab: "Previous Tab",
            close_other_tabs: "Close Other Tabs",
            close_tab: "Close Tab",
            navigation_group: "Navigation",
            back_page: "Previous Page",
            forward_page: "Next Page",
            refresh: "Refresh",
            force_refresh: "Force Refresh",
            home_page: "Home Page",
            search_group: "Search & URL",
            address_bar: "Address Bar (URL)",
            find_in_page: "Find in Page",
            find_next: "Next Match",
            find_prev: "Previous Match",
            view_group: "View",
            fullscreen: "Fullscreen",
            reader_mode: "Reader Mode",
            reset_zoom: "Reset Zoom (100%)",
            view_source: "View Page Source",
            tools_group: "Tools",
            history: "History",
            downloads: "Downloads",
            bookmarks_manager: "Bookmarks Manager",
            dev_tools: "Developer Tools",
            windows_group: "Windows & Security",
            incognito: "Private Browsing",
            new_window: "New Window",
            add_bookmark: "Bookmark This Page",
            print_page: "Print Page",
        },
    ),
    (
        "fr",
        BrowserTexts {
            profile_label: "Navigateurs Web",
            new_tab: "Nouvel Onglet",
            tabs_group: "Onglets",
            reopen_closed_tab: "Rouvrir Onglet Fermé",
            next_tab: "Onglet Suivant",
            prev_tab: "Onglet Précédent",
            close_other_tabs: "Fermer les Autres Onglets",
            close_tab: "Fermer Onglet",
            navigation_group: "Navigation",
            back_page: "Page Précédente",
            forward_page: "Page Suivante",
            refresh: "Actualiser",
            force_refresh: "Forcer l'Actualisation",
            home_page: "Page d'Accueil",
            search_group: "Recherche & URL",
            address_bar: "Barre d'adresse (URL)",
            find_in_page: "Rechercher dans la page",
            find_next: "Résultat suivant",
            find_prev: "Résultat précédent",
            view_group: "Affichage",
            fullscreen: "Plein Écran",
            reader_mode: "Mode Lecture",
            reset_zoom: "Réinitialiser Zoom (100%)",
            view_source: "Code Source de la page",
            tools_group: "Outils",
            history: "Historique",
            downloads: "Téléchargements",
            bookmarks_manager: "Gestionnaire des Favoris",
            dev_tools: "Inspecteur Développeur",
            windows_group: "Fenêtres & Sécurité",
            incognito: "Navigation Privée",
            new_window: "Nouvelle Fenêtre",
            add_bookmark: "Ajouter aux Favoris",
            print_page: "Imprimer la page",
        },
    ),
    (
        "es",
        BrowserTexts {
            profile_label: "Navegadores Web",
            new_tab: "Nueva Pestaña",
            tabs_group: "Pestañas",
            reopen_closed_tab: "Reabrir Pestaña Cerrada",
            next_tab: "Pestaña Siguiente",
            prev_tab: "Pestaña Anterior",
            close_other_tabs: "Cerrar Otras Pestañas",
            close_tab: "Cerrar Pestaña",
            navigation_group: "Navegación",
            back_page: "Página Anterior",
            forward_page: "Página Siguiente",
            refresh: "Actualizar",
            force_refresh: "Forzar Actualización",
            home_page: "Página de Inicio",
            search_group: "Búsqueda & URL",
            address_bar: "Barra de direcciones (URL)",
            find_in_page: "Buscar en la página",
            find_next: "Resultado siguiente",
            find_prev: "Resultado anterior",
            view_group: "Vista",
            fullscreen: "Pantalla Completa",
            reader_mode: "Modo Lectura",
            reset_zoom: "Restablecer Zoom (100%)",
            view_source: "Código Fuente de la página",
            tools_group: "Herramientas",
            history: "Historial",
            downloads: "Descargas",
            bookmarks_manager: "Administrador de Marcadores",
            dev_tools: "Herramientas de Desarrollador",
            windows_group: "Ventanas & Seguridad",
            incognito: "Navegación Privada",
            new_window: "Nueva Ventana",
            add_bookmark: "Añadir a Marcadores",
            print_page: "Imprimir página",
        },
    ),
];

pub fn browser_texts(lang: &str) -> &'static BrowserTexts {
    super::find_texts_for_lang(BROWSER_TRANSLATIONS, lang)
}

#[allow(dead_code)]
pub fn browser_profile() -> AppProfileConfig {
    browser_profile_for_lang("en")
}

pub fn browser_profile_for_lang(lang: &str) -> AppProfileConfig {
    let t = browser_texts(lang);
    let browser_ring = RingMenuConfig {
        default_color: default_ring_color(),
        default_active_color: default_ring_active_color(),
        animation: RingAnimation::default(),
        trigger_mode: RingTriggerMode::default(),
        wheel_navigation: true,
        max_slots: 16,
        glow_effect: default_true(),
        pulse_effect: default_true(),
        items: vec![
            // Slot 0: Quick action New Tab
            RingMenuItemConfig {
                slot: 0,
                label: t.new_tab.to_string(),
                translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.new_tab),
                icon: "➕".to_string(),
                action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "t".to_string()] }),
                items: vec![],
                auto_close: true,
                color: None,
                active_color: None,
            },

            // Slot 1: Tabs management group
            RingMenuItemConfig {
                slot: 1,
                label: t.tabs_group.to_string(),
                translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.tabs_group),
                icon: "📑".to_string(),
                action: None,
                auto_close: true,
                color: None,
                active_color: None,
                items: vec![
                    SubMenuItemConfig {
                        label: t.reopen_closed_tab.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.reopen_closed_tab),
                        icon: "↩️".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "SHIFT".to_string(), "t".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.next_tab.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.next_tab),
                        icon: "⏭️".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "Tab".to_string()] }),
                        items: vec![],
                        auto_close: false,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.prev_tab.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.prev_tab),
                        icon: "⏮️".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "SHIFT".to_string(), "Tab".to_string()] }),
                        items: vec![],
                        auto_close: false,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.close_other_tabs.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.close_other_tabs),
                        icon: "🗙".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "SHIFT".to_string(), "w".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                ],
            },

            // Slot 2: Quick action Close Tab
            RingMenuItemConfig {
                slot: 2,
                label: t.close_tab.to_string(),
                translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.close_tab),
                icon: "❌".to_string(),
                action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "w".to_string()] }),
                items: vec![],
                auto_close: true,
                color: None,
                active_color: None,
            },

            // Slot 3: History & Navigation group
            RingMenuItemConfig {
                slot: 3,
                label: t.navigation_group.to_string(),
                translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.navigation_group),
                icon: "🧭".to_string(),
                action: None,
                auto_close: true,
                color: None,
                active_color: None,
                items: vec![
                    SubMenuItemConfig {
                        label: t.back_page.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.back_page),
                        icon: "⬅️".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["ALT".to_string(), "Left".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.forward_page.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.forward_page),
                        icon: "➡️".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["ALT".to_string(), "Right".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.refresh.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.refresh),
                        icon: "🔄".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "r".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.force_refresh.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.force_refresh),
                        icon: "⚡".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "SHIFT".to_string(), "r".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.home_page.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.home_page),
                        icon: "🏠".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["ALT".to_string(), "Home".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                ],
            },

            // Slot 4: Search & URL group
            RingMenuItemConfig {
                slot: 4,
                label: t.search_group.to_string(),
                translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.search_group),
                icon: "🔍".to_string(),
                action: None,
                auto_close: true,
                color: None,
                active_color: None,
                items: vec![
                    SubMenuItemConfig {
                        label: t.address_bar.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.address_bar),
                        icon: "🌐".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "l".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.find_in_page.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.find_in_page),
                        icon: "🔎".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "f".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.find_next.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.find_next),
                        icon: "⬇️".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["F3".to_string()] }),
                        items: vec![],
                        auto_close: false,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.find_prev.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.find_prev),
                        icon: "⬆️".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["SHIFT".to_string(), "F3".to_string()] }),
                        items: vec![],
                        auto_close: false,
                        color: None,
                        active_color: None,
                    },
                ],
            },

            // Slot 5: View group
            RingMenuItemConfig {
                slot: 5,
                label: t.view_group.to_string(),
                translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.view_group),
                icon: "🖥️".to_string(),
                action: None,
                auto_close: true,
                color: None,
                active_color: None,
                items: vec![
                    SubMenuItemConfig {
                        label: t.fullscreen.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.fullscreen),
                        icon: "⛶".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["F11".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.reader_mode.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.reader_mode),
                        icon: "📖".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["F9".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.reset_zoom.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.reset_zoom),
                        icon: "🔍".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "0".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.view_source.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.view_source),
                        icon: "📜".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "u".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                ],
            },

            // Slot 6: Tools group
            RingMenuItemConfig {
                slot: 6,
                label: t.tools_group.to_string(),
                translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.tools_group),
                icon: "🧰".to_string(),
                action: None,
                auto_close: true,
                color: None,
                active_color: None,
                items: vec![
                    SubMenuItemConfig {
                        label: t.history.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.history),
                        icon: "🕒".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "h".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.downloads.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.downloads),
                        icon: "📥".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "j".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.bookmarks_manager.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.bookmarks_manager),
                        icon: "⭐".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "SHIFT".to_string(), "o".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.dev_tools.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.dev_tools),
                        icon: "🛠️".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["F12".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                ],
            },

            // Slot 7: Windows & Security group
            RingMenuItemConfig {
                slot: 7,
                label: t.windows_group.to_string(),
                translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.windows_group),
                icon: "🛡️".to_string(),
                action: None,
                auto_close: true,
                color: None,
                active_color: None,
                items: vec![
                    SubMenuItemConfig {
                        label: t.incognito.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.incognito),
                        icon: "🕶️".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "SHIFT".to_string(), "p".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.new_window.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.new_window),
                        icon: "🪟".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "n".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.add_bookmark.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.add_bookmark),
                        icon: "🔖".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "d".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                    SubMenuItemConfig {
                        label: t.print_page.to_string(),
                        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.print_page),
                        icon: "🖨️".to_string(),
                        action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "p".to_string()] }),
                        items: vec![],
                        auto_close: true,
                        color: None,
                        active_color: None,
                    },
                ],
            },
        ],
    };

    AppProfileConfig {
        app_id: "firefox; org.mozilla.firefox; brave; brave-browser; google-chrome; google-chrome-stable; chromium; chromium-browser; zen; zen-alpha; opera; vivaldi; microsoft-edge; floorp; epiphany".to_string(),
        label: t.profile_label.to_string(),
        translations: super::build_translation_map(BROWSER_TRANSLATIONS, |x| x.profile_label),
        logo_path: "assets/apps/firefox.webp".to_string(),
        ring_menu: Some(browser_ring),
    }
}
