use crate::config::actions::ButtonActionConfig;
use crate::config::rings::*;
use crate::config::{Config, GeneralConfig};
use crate::devices::{BTN_GESTURES_CODE, BTN_RING_CODE};
use std::collections::HashMap;
use super::default_app_profiles_for_lang;

#[derive(Debug, Clone, Copy)]
pub struct DefaultConfigTexts {
    pub screenshot: &'static str,
    // AI Tools
    pub ai_tools: &'static str,
    pub chatgpt: &'static str,
    pub ask_perplexity: &'static str,
    pub claude: &'static str,
    pub deepseek: &'static str,
    // Media
    pub media: &'static str,
    pub play_pause: &'static str,
    pub next_track: &'static str,
    pub prev_track: &'static str,
    pub volume_up: &'static str,
    pub volume_down: &'static str,
    pub mute_toggle: &'static str,
    // Windows & Workspaces
    pub windows_workspace: &'static str,
    pub overview: &'static str,
    pub snap_left: &'static str,
    pub snap_right: &'static str,
    pub maximize: &'static str,
    pub next_desktop: &'static str,
    // Direct tools
    pub terminal: &'static str,
    pub clipboard: &'static str,
    pub web_browser: &'static str,
    // System
    pub system: &'static str,
    pub settings: &'static str,
    pub lock_session: &'static str,
    pub log_out: &'static str,
    pub power_off: &'static str,
}

pub const DEFAULT_CONFIG_TRANSLATIONS: &[(&str, DefaultConfigTexts)] = &[
    (
        "en",
        DefaultConfigTexts {
            screenshot: "Screenshot",
            ai_tools: "AI Tools",
            chatgpt: "ChatGPT",
            ask_perplexity: "Perplexity AI",
            claude: "Claude AI",
            deepseek: "DeepSeek",
            media: "Media",
            play_pause: "Play / Pause",
            next_track: "Next Track",
            prev_track: "Previous Track",
            volume_up: "Volume +",
            volume_down: "Volume -",
            mute_toggle: "Mute",
            windows_workspace: "Windows & Workspace",
            overview: "Overview",
            snap_left: "Snap Left",
            snap_right: "Snap Right",
            maximize: "Maximize Window",
            next_desktop: "Next Desktop",
            terminal: "Terminal",
            clipboard: "Clipboard History",
            web_browser: "Web Browser",
            system: "System",
            settings: "Settings",
            lock_session: "Lock Session",
            log_out: "Log Out",
            power_off: "Power Off",
        },
    ),
    (
        "fr",
        DefaultConfigTexts {
            screenshot: "Capture d'écran",
            ai_tools: "Outils IA",
            chatgpt: "ChatGPT",
            ask_perplexity: "Perplexity AI",
            claude: "Claude AI",
            deepseek: "DeepSeek",
            media: "Médias",
            play_pause: "Lecture / Pause",
            next_track: "Piste Suivante",
            prev_track: "Piste Précédente",
            volume_up: "Volume +",
            volume_down: "Volume -",
            mute_toggle: "Couper le Son",
            windows_workspace: "Fenêtres & Espaces",
            overview: "Aperçu des Fenêtres",
            snap_left: "Ancrer à Gauche",
            snap_right: "Ancrer à Droite",
            maximize: "Maximiser la Fenêtre",
            next_desktop: "Bureau Suivant",
            terminal: "Terminal",
            clipboard: "Historique Presse-papier",
            web_browser: "Navigateur Web",
            system: "Système",
            settings: "Paramètres",
            lock_session: "Verrouiller la Session",
            log_out: "Fermer la Session",
            power_off: "Éteindre",
        },
    ),
    (
        "es",
        DefaultConfigTexts {
            screenshot: "Captura de Pantalla",
            ai_tools: "Herramientas IA",
            chatgpt: "ChatGPT",
            ask_perplexity: "Perplexity AI",
            claude: "Claude AI",
            deepseek: "DeepSeek",
            media: "Medios",
            play_pause: "Reproducir / Pausa",
            next_track: "Pista Siguiente",
            prev_track: "Pista Anterior",
            volume_up: "Volumen +",
            volume_down: "Volumen -",
            mute_toggle: "Silenciar",
            windows_workspace: "Ventanas y Espacio",
            overview: "Vista General",
            snap_left: "Ajustar a la Izquierda",
            snap_right: "Ajustar a la Derecha",
            maximize: "Maximizar Ventana",
            next_desktop: "Siguiente Escritorio",
            terminal: "Terminal",
            clipboard: "Historial Portapapeles",
            web_browser: "Navegador Web",
            system: "Sistema",
            settings: "Configuración",
            lock_session: "Bloquear Sesión",
            log_out: "Cerrar Sesión",
            power_off: "Apagar",
        },
    ),
];

pub fn default_config_texts(lang: &str) -> &'static DefaultConfigTexts {
    super::find_texts_for_lang(DEFAULT_CONFIG_TRANSLATIONS, lang)
}

pub fn default_config() -> Config {
    let lang = crate::utils::i18n::detect_system_language();
    default_config_for_lang(&lang)
}

pub fn default_config_for_lang(lang: &str) -> Config {
    let t = default_config_texts(lang);

    let mut buttons = HashMap::new();
    buttons.insert(BTN_RING_CODE, ButtonActionConfig::ShowRingMenu);
    buttons.insert(BTN_GESTURES_CODE, ButtonActionConfig::KeyCombo { keys: vec!["Super".to_string()] });

    let items = vec![
        // Slot 0: Screenshot
        RingMenuItemConfig {
            slot: 0,
            label: t.screenshot.to_string(),
            translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.screenshot),
            icon: "📸".to_string(),
            action: Some(ButtonActionConfig::KeyCombo { keys: vec!["Print".to_string()] }),
            items: vec![],
            auto_close: true,
            color: Some("#3D2B14".to_string()),
            active_color: Some("#F59E0B".to_string()),
        },
        // Slot 1: AI Tools (ChatGPT, Perplexity, Claude, DeepSeek)
        RingMenuItemConfig {
            slot: 1,
            label: t.ai_tools.to_string(),
            translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.ai_tools),
            icon: "✨".to_string(),
            action: None,
            auto_close: true,
            color: Some("#2E1E4A".to_string()),
            active_color: Some("#8B5CF6".to_string()),
            items: vec![
                SubMenuItemConfig {
                    label: t.chatgpt.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.chatgpt),
                    icon: "🤖".to_string(),
                    action: Some(ButtonActionConfig::Command { cmd: "xdg-open https://chatgpt.com".to_string() }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#0E2A22".to_string()),
                    active_color: Some("#10A37F".to_string()),
                },
                SubMenuItemConfig {
                    label: t.ask_perplexity.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.ask_perplexity),
                    icon: "✳️".to_string(),
                    action: Some(ButtonActionConfig::Command { cmd: "xdg-open https://perplexity.ai".to_string() }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#132338".to_string()),
                    active_color: Some("#38BDF8".to_string()),
                },
                SubMenuItemConfig {
                    label: t.claude.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.claude),
                    icon: "🟣".to_string(),
                    action: Some(ButtonActionConfig::Command { cmd: "xdg-open https://claude.ai".to_string() }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#3B2212".to_string()),
                    active_color: Some("#D97706".to_string()),
                },
                SubMenuItemConfig {
                    label: t.deepseek.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.deepseek),
                    icon: "⚡".to_string(),
                    action: Some(ButtonActionConfig::Command { cmd: "xdg-open https://chat.deepseek.com".to_string() }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#131E3D".to_string()),
                    active_color: Some("#3B82F6".to_string()),
                },
            ],
        },
        // Slot 2: Media (Play/Pause, Next, Prev, Vol+, Vol-, Mute)
        RingMenuItemConfig {
            slot: 2,
            label: t.media.to_string(),
            translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.media),
            icon: "🎵".to_string(),
            action: None,
            auto_close: true,
            color: Some("#3D162B".to_string()),
            active_color: Some("#EC4899".to_string()),
            items: vec![
                SubMenuItemConfig {
                    label: t.play_pause.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.play_pause),
                    icon: "⏯️".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["PlayPause".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#103322".to_string()),
                    active_color: Some("#10B981".to_string()),
                },
                SubMenuItemConfig {
                    label: t.next_track.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.next_track),
                    icon: "⏭️".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["NextSong".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#1E1E42".to_string()),
                    active_color: Some("#6366F1".to_string()),
                },
                SubMenuItemConfig {
                    label: t.prev_track.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.prev_track),
                    icon: "⏮️".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["PreviousSong".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#1E1E42".to_string()),
                    active_color: Some("#6366F1".to_string()),
                },
                SubMenuItemConfig {
                    label: t.volume_up.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.volume_up),
                    icon: "🔊".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["VolumeUp".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#12233D".to_string()),
                    active_color: Some("#3B82F6".to_string()),
                },
                SubMenuItemConfig {
                    label: t.volume_down.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.volume_down),
                    icon: "🔉".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["VolumeDown".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#12233D".to_string()),
                    active_color: Some("#3B82F6".to_string()),
                },
                SubMenuItemConfig {
                    label: t.mute_toggle.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.mute_toggle),
                    icon: "🔇".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["Mute".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#3D1414".to_string()),
                    active_color: Some("#EF4444".to_string()),
                },
            ],
        },
        // Slot 3: Windows & Workspaces (Overview, Snap Left, Snap Right, Maximize, Next Desktop)
        RingMenuItemConfig {
            slot: 3,
            label: t.windows_workspace.to_string(),
            translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.windows_workspace),
            icon: "🪟".to_string(),
            action: None,
            auto_close: true,
            color: Some("#162847".to_string()),
            active_color: Some("#3B82F6".to_string()),
            items: vec![
                SubMenuItemConfig {
                    label: t.overview.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.overview),
                    icon: "🪟".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["Super".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#12233D".to_string()),
                    active_color: Some("#3B82F6".to_string()),
                },
                SubMenuItemConfig {
                    label: t.snap_left.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.snap_left),
                    icon: "⬅️".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["Super".to_string(), "Left".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#25193D".to_string()),
                    active_color: Some("#8B5CF6".to_string()),
                },
                SubMenuItemConfig {
                    label: t.snap_right.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.snap_right),
                    icon: "➡️".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["Super".to_string(), "Right".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#25193D".to_string()),
                    active_color: Some("#8B5CF6".to_string()),
                },
                SubMenuItemConfig {
                    label: t.maximize.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.maximize),
                    icon: "🔼".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["Super".to_string(), "Up".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#103322".to_string()),
                    active_color: Some("#10B981".to_string()),
                },
                SubMenuItemConfig {
                    label: t.next_desktop.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.next_desktop),
                    icon: "💻".to_string(),
                    action: Some(ButtonActionConfig::KeyCombo { keys: vec!["CTRL".to_string(), "ALT".to_string(), "Down".to_string()] }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#0D2D36".to_string()),
                    active_color: Some("#06B6D4".to_string()),
                },
            ],
        },
        // Slot 4: Terminal
        RingMenuItemConfig {
            slot: 4,
            label: t.terminal.to_string(),
            translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.terminal),
            icon: "💻".to_string(),
            action: Some(ButtonActionConfig::Command { cmd: "gnome-terminal || ptyxis || kgx || konsole || alacritty || kitty || x-terminal-emulator || xterm".to_string() }),
            items: vec![],
            auto_close: true,
            color: Some("#123326".to_string()),
            active_color: Some("#10B981".to_string()),
        },
        // Slot 5: Clipboard History (Super+V)
        RingMenuItemConfig {
            slot: 5,
            label: t.clipboard.to_string(),
            translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.clipboard),
            icon: "📋".to_string(),
            action: Some(ButtonActionConfig::KeyCombo { keys: vec!["Super".to_string(), "v".to_string()] }),
            items: vec![],
            auto_close: true,
            color: Some("#0E333D".to_string()),
            active_color: Some("#06B6D4".to_string()),
        },
        // Slot 6: Web Browser
        RingMenuItemConfig {
            slot: 6,
            label: t.web_browser.to_string(),
            translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.web_browser),
            icon: "🌐".to_string(),
            action: Some(ButtonActionConfig::Command { cmd: "xdg-open https://google.com".to_string() }),
            items: vec![],
            auto_close: true,
            color: Some("#20224A".to_string()),
            active_color: Some("#6366F1".to_string()),
        },
        // Slot 7: System (Settings, Lock, Log Out, Power Off)
        RingMenuItemConfig {
            slot: 7,
            label: t.system.to_string(),
            translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.system),
            icon: "⚙️".to_string(),
            action: None,
            auto_close: true,
            color: Some("#262C38".to_string()),
            active_color: Some("#64748B".to_string()),
            items: vec![
                SubMenuItemConfig {
                    label: t.settings.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.settings),
                    icon: "⚙️".to_string(),
                    action: Some(ButtonActionConfig::Command { cmd: "gnome-control-center || systemsettings || xfce4-settings-manager".to_string() }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#1E242E".to_string()),
                    active_color: Some("#64748B".to_string()),
                },
                SubMenuItemConfig {
                    label: t.lock_session.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.lock_session),
                    icon: "🔒".to_string(),
                    action: Some(ButtonActionConfig::Command { cmd: "loginctl lock-session".to_string() }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#3B2512".to_string()),
                    active_color: Some("#F59E0B".to_string()),
                },
                SubMenuItemConfig {
                    label: t.log_out.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.log_out),
                    icon: "🚪".to_string(),
                    action: Some(ButtonActionConfig::Command { cmd: "loginctl terminate-user \"\"".to_string() }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#3D1C10".to_string()),
                    active_color: Some("#EA580C".to_string()),
                },
                SubMenuItemConfig {
                    label: t.power_off.to_string(),
                    translations: super::build_translation_map(DEFAULT_CONFIG_TRANSLATIONS, |x| x.power_off),
                    icon: "⏻".to_string(),
                    action: Some(ButtonActionConfig::Command { cmd: "systemctl poweroff".to_string() }),
                    items: vec![],
                    auto_close: true,
                    color: Some("#3D1414".to_string()),
                    active_color: Some("#DC2626".to_string()),
                },
            ],
        },
    ];

    Config {
        general: GeneralConfig {
            device_name: "Logitech USB Receiver Mouse".to_string(),
            theme: "dark".to_string(),
            language: "system".to_string(),
            autostart_daemon: false,
            dev_mode: false,
            mode_editor: false,
            device_profile: "auto".to_string(),
        },
        buttons,
        ring_menu: RingMenuConfig {
            default_color: default_ring_color(),
            default_active_color: default_ring_active_color(),
            items,
            animation: RingAnimation::default(),
            trigger_mode: RingTriggerMode::default(),
            wheel_navigation: default_true(),
            max_slots: default_max_slots(),
            glow_effect: default_true(),
            pulse_effect: default_true(),
        },
        app_profiles: default_app_profiles_for_lang(lang),
        actions: crate::config::actions::default_actions_catalog_for_lang(lang),
    }
}
